
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: gorettinbg/apirestgo-api-go:latest  # imagen en Docker Hub
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: api-config

